"CREATE DATABASE lalala;"
"USE lalala;"
"CREATE TABLE lala(id int NOT NULL AUTO_INCREMENT,la1 int , la2 int, PRIMARY KEY (id));"
"SOURCE C:\Users\Dann\Desktop\topicos;"
"INSERT INTO lala ( la1 , la2 ) VALUES ('nombre',20);"
"INSERT INTO lala ( la1 , la2 ) VALUES ('nombre',20);"
